### ISSUE TITLE
While making build getting Failed to verify bitcode in MoEngage.framework/MoEngage error

### ISSUE THREAD

**Issue by Biplab2014** [moengage/MoEngage-iOS-SDK#12]
Failed to verify bitcode in MoEngage.framework/MoEngage:
error: Linker option verification failed for bundle /var/folders/f_/z63_qpxj2q73twv2wp4d2l3c0000gn/T/MoEngagexiUorA/MoEngage.armv7.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.0.0)

**Comment by ChengappaMoEngage** [comment]
@Biplab2014 : Yes, we have encountered this error. This happens when you use our latest SDK versions(built-in Xcode 11) in previous versions of Xcode i.e, Xcode 10.

This is because of the bitcode generated for our framework by Xcode 11 is not compatible with older versions of Xcode.

 Please update to the latest version of Xcode and you should not see this issue.
