### ISSUE TITLE
Issue on Archieving of Distributing App

### ISSUE THREAD

**Issue by dpkbnsl26** [moengage/MoEngage-iOS-SDK#14]
Hi Team 
I am getting "ipatool failed with an exception moengage".  
Please check attached image & help us on same.
<img width="1268" alt="moENgage" src="https://user-images.githubusercontent.com/3415999/77535038-dfc10800-6ebf-11ea-8f52-ff71ef00f011.png">

**Comment by ChengappaMoEngage** [comment]
@dpkbnsl26 The issue was because of the weak linking of MoEngageInApp and MOGeofence frameworks which wasn't done correctly. We have fixed this now with SDK [version 6.0.2](https://docs.moengage.com/docs/release-notes#section-v602). Please update and try once more, you shouldn't be seeing this issue.
