### ISSUE TITLE
Fetch all received notifications

### ISSUE THREAD

**Issue by RR12** [moengage/MoEngage-iOS-SDK#6]
So, we have a specification to show all received notification (even those notifications that not opened yet by the user).
So for example, an user received 5 notifications, and that user only click 1 notification from those 5. Is there any specific API that provided by this SDK to get all those 5 notifications?

**Comment by ChengappaMoEngage** [comment]
Hi @RR12, In an iOS App and hence also MoEngage SDK you get the callback only when notification is clicked by the user, therefore the notifications clicked by a user is saved by the SDK locally and you will be able to obtain them using `[MOInbox getInboxMessages];`. 

For obtaining the unclicked notifications we will have to enable storing of notifications in our backend(the same will be fetched by SDK and provided to you by the same method). To start storing notifications in our backend could you please raise a request from your MoEngage dashboard, this is so that we know for which moengage account this has to be enabled.

**Comment by RR12** [comment]
Hi @ChengappaMoEngage thank you for the information.
